import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins, Yellowtail } from "next/font/google";
import "./globals.css";
import Providers from "./Providers";
import AuthBootstrap from "./AuthBootstrap";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "500", "600", "700"],
});

const yellowtail = Yellowtail({
  subsets: ["latin"],
  variable: "--font-yellowtail",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Whisp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${yellowtail.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        <Providers>
          <AuthBootstrap />
          {children}
        </Providers>
      </body>
    </html>
  );
}
