import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "./styles/globals.css";
import "./styles/emoji-picker.css"
import Providers from "./Providers";
import AuthBootstrap from "./AuthBootstrap";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-family",
});
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-family",
});

export const metadata: Metadata = {
  title: "Whisp",
  description: "Generated by create next app",
};

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Providers>
          <AuthBootstrap />
          {children}
        </Providers>
      </body>
    </html>
  );
}